ENTESB-15225: Adds affinity and toleration values on install
syndesisio/syndesis pull request #9387
Opened 2021-02-24 16:11 UTC by phantomjinx

* During install phase, adds the affinity and toleration values to the
  infrastructure deployment configs
 * Not been possible previously due to not having the deployment configs
   readily to hand as typed objects

* install.go
 * Processes each resource on install and determines if they're a DC
 * If so, adds in the content from the Syndesis resource as blocks
 * Should the syntax in the Syndesis resource be incorrect then there will
   be errors in the operator log

* install_test.go
 * Tests for the PreProcessDeploymentConfig function

2021-02-24 18:57 UTC, claudio4j requested changes
I just noticed that syndesis-jaeger is missing the affinity/tolerations setting. 
https://www.jaegertracing.io/docs/1.13/operator/#finer-grained-configuration
The api looks the same.
This is missing in pod_scheduling.go which I am going to fix.

2021-02-25 08:42 UTC, phantomjinx commented
retest this please

2021-02-25 11:39 UTC, phantomjinx commented
QE Jenkins PR Build 1.12.x test seems to fail on downloading a helloworld export. Is this temperamental or something that needs fixing?
@avano

2021-02-25 11:40 UTC, phantomjinx commented
> I just noticed that syndesis-jaeger is missing the affinity/tolerations setting.
> https://www.jaegertracing.io/docs/1.13/operator/#finer-grained-configuration
> The api looks the same.
> This is missing in pod_scheduling.go which I am going to fix.

Does that mean that the addon resources need to pass through preProcessDeploymentConfig function as well then?

2021-02-25 11:43 UTC, claudio4j commented
> Does that mean that the addon resources need to pass through preProcessDeploymentConfig function as well then?
Yes, as the syndesis-jaeger is a infrastructure workload that users could allocate to specific nodes.

2021-02-25 12:02 UTC, avano commented
@phantomjinx I'm going to check what is going on

2021-02-25 13:05 UTC, avano commented
retest this please

2021-02-25 18:41 UTC, claudio4j approved these changes

2021-03-01 13:38 UTC, merged