fix(c/sql): stored procedure/function metadata
syndesisio/syndesis pull request #9592
Opened 2021-05-06 20:05 UTC by zregvart

When fetching metadata for functions in PostgreSQL we need to use stored
procedure metadata, not function metadata as it returns nothing.

Ref. issues.redhat.com/browse/ENTESB-16358

fix(c/sql): make sure test tear down is done (766e285)

We need to make sure that any object we create is dropped in the test.
Otherwise we might get flaky tests that depend on the order of
execution.

(cherry picked from commit fbcbfeac2a2111e7f43f60458b88a7472bff5778)

2021-05-07 09:29 UTC, zregvart commented
retest this please

2021-05-07 11:43 UTC, avano commented
retest this please

2021-05-07 23:48 UTC, claudio4j requested changes

2021-05-07 23:48 UTC, claudio4j commented on app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java
>      public static StoredProcedureMetadata getFunctionOrProcedureMetadata(final Connection connection, final String catalog,
As there is no fetchFunctionColumns call, renaming the method back to getProcedureMetadata and adding a comment about why not using fetchFunctionColumns.

2021-05-10 13:00 UTC, zregvart commented
Thanks for the review, @claudio4j can you have another look?

2021-05-10 13:13 UTC, claudio4j approved these changes

2021-05-10 17:41 UTC, merged