fix(ui): additional step for SOAP service and port
syndesisio/syndesis pull request #9658
Opened 2021-06-28 21:12 UTC by zregvart

We used to have two screens on the "Imported Operations" step, akka
review step of the custom API client wizard. That caused issues with
error handling: the screen to specify service and port would throw an
`Error` if the provided WSDL file cannot be parsed. So in #9633 instead
of reaching this screen a notification would appear indicating of this
error situation. Unfortunately, this also changed the flow for the
OpenAPI. So when an error was generated editing the successfully parsed
OpenAPI document we would render the first screen (upload) of the wizard
and show the error notification. And in process loose any changes user
has made to the document.

This instead adds an additional step in the wizard "Additional
Configuration" to specify service/port for WSDL documents, and is
skipped for OpenAPI documents, also changing the order of the
"Imported Operations" (review) screen, so that it precedes this new
screen. This way we won't `Error`-out in trying to access nonexistent
data, as it could not be parsed.

Ref. https://issues.redhat.com/browse/ENTESB-16902

2021-06-28 21:14 UTC, zregvart commented
cc @gashcrumb, @mkralik3 this is what I think a _proper_ fix would do. It's quite big as you can see. It's also more work to adapt QE tests and probably needs adjusting the docs.
For `1.12.x` I can try to create a quick fix, one that would not be that _proper_. Or we can bite the bullet, up for discussion.

2021-07-05 12:45 UTC, kahboom commented
@zregvart - I mean, it's a lot of changes, but I do like the idea of moving the Service/Port config onto a separate page. I've gone through the changes and tested the branch locally, and it looks good, with a few small requests:

1. Please update the story filenames to match the step number; it just makes it _much_ easier to find them when you need to reference them. This probably also means adding another story for the new step/page.
2. Remove the footer in the `ApiConnectorCreatorService` (found in `packages/ui/src/Customization/apiClientConnectors/create`) since it's no longer needed, otherwise produces a duplicate Next button:

![Screen Shot 2021-07-02 at 11 56 08](https://user-images.githubusercontent.com/3844502/124271253-25de3000-db35-11eb-8632-c6d029641f55.png)

2021-07-05 12:45 UTC, kahboom requested changes
@zregvart - I mean, it's a lot of changes, but I do like the idea of moving the Service/Port config onto a separate page. I've gone through the changes and tested the branch locally, and it looks good, with a few small requests:

1. Please update the story filenames to match the step number; it just makes it _much_ easier to find them when you need to reference them. This probably also means adding another story for the new step/page.
2. Remove the footer in the `ApiConnectorCreatorService` (found in `packages/ui/src/Customization/apiClientConnectors/create`) since it's no longer needed, otherwise produces a duplicate Next button:

![Screen Shot 2021-07-02 at 11 56 08](https://user-images.githubusercontent.com/3844502/124271253-25de3000-db35-11eb-8632-c6d029641f55.png)

2021-07-05 12:45 UTC, kahboom commented on app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
> +      "address": "Address",
Happy to see it's not just me that appreciates alphabetical order 😆

2021-07-06 09:28 UTC, zregvart commented on app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
> +      "address": "Address",
Yeah I did that in #9652 to ease with OpenAPI JSON files copied between server and UI, but in general that (with time) will help us with merges/backports...

2021-07-06 09:28 UTC, zregvart commented
Fat fingered that. Thanks @kahboom for the review, I'll get to fixing this.

2021-10-13 20:52 UTC, zregvart commented
Many new fixes were added for this, more details in the commit messages.

2021-10-13 20:55 UTC, zregvart commented
This also should fix https://issues.redhat.com/browse/ENTESB-17281 via a671e49

2021-10-14 07:01 UTC, Delawen commented
Rerunning jobs because one failed. Just in case.

2021-10-14 09:19 UTC, zregvart commented
> Rerunning jobs because one failed. Just in case.

There was a TSLint issue in the UI, should be okay now.

2021-10-14 10:08 UTC, kahboom approved these changes

2021-10-14 10:49 UTC, merged