feat: set integration pod environment variables
syndesisio/syndesis pull request #9747
Opened 2021-10-05 20:16 UTC by zregvart

This adds the ability to add custom environment variables set on the
DeploymentConfig and available in the container of the running
integration Pod on the Save integration screen of the integration edit
wizard.

Ref. https://issues.redhat.com/browse/ENTESB-16398

2021-10-05 21:20 UTC, zregvart commented
For reviewers, this _is_ a quick & dirty way of implementing this functionality, stuff that I know can be improved:
 - there are no tests
 - there is no (new) inline documentation
 - ~~I did not localize the UI~~
 - binding is iffy at the least
 - UI looks awkward

Screenshot:
![Screenshot 2021-10-05 at 23-11-38 Save the integration - Syndesis](https://user-images.githubusercontent.com/1306050/136104324-28c5b378-c7d1-4d76-b67a-f4cd60d4997c.png)

2021-10-06 14:13 UTC, zregvart commented
Converted to draft, most likely won't make it to 1.13.x, so let's target for 1.14.x

2021-10-27 11:10 UTC, zregvart commented
I'm happier with this version, the environment section is now incorporated into the auto-form of the save page instead of being a separate component, so no more bind-in-render. Still would benefit from some UX help.

![localhost_3000_integrations_](https://user-images.githubusercontent.com/1306050/139054952-0779c215-fca5-418d-a5ba-b119a65f0487.png)

2021-10-27 13:48 UTC, phantomjinx approved these changes
LGTM - but another set of eyes would be advantagous

2021-10-27 16:09 UTC, claudio4j requested changes

2021-10-27 16:09 UTC, claudio4j commented on app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
>              final Map<String, EnvVar> envVarMap = new HashMap<>();
The environment variables are added only for existing integrations, this logic to add the environment variables is missing when there is a new integration, see line 417.

2021-10-27 21:24 UTC, zregvart commented on app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
>              final Map<String, EnvVar> envVarMap = new HashMap<>();
Good catch, I think 6e249d9b944910a5e31c908abfb338cfdddf51ae should fix that, can you have another look?

2021-10-27 22:31 UTC, claudio4j commented on app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
>              final Map<String, EnvVar> envVarMap = new HashMap<>();
The `deploymentData.getEnvironment()` is empty in `ensureDeploymentConfig` method, I didn't investigate why.

2021-10-28 09:29 UTC, zregvart commented on app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
>              final Map<String, EnvVar> envVarMap = new HashMap<>();
Was at least one environment variable set for the Integration you were testing with?

Should be set from here:

https://github.com/syndesisio/syndesis/pull/9747/files#diff-792449018802d5dc5b366781e0a37a4f0d7b3d033400b95260e7953d8e9ffa1eR153

2021-10-28 15:25 UTC, claudio4j commented on app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
>              final Map<String, EnvVar> envVarMap = new HashMap<>();
The `integration.getEnvironment()` is empty in `PublishHandler.java createDeploymentData()`. I built syndesis with `syndesis build -b -m ui-react,s2i -f -i`

2021-10-28 15:44 UTC, claudio4j commented on app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
>              final Map<String, EnvVar> envVarMap = new HashMap<>();
common/model/target/generated-sources/annotations/io/syndesis/common/model/integration/ImmutableIntegration.java was missing the WithEnvironment attributes, just did `mvn clean` in common dir, the ImmutableIntegration.java was created correctly. I just forgot to wipe old stuff build earlier. Sorry.

2021-10-28 15:45 UTC, claudio4j approved these changes

2021-10-28 19:40 UTC, merged

2021-10-28 19:41 UTC, kahboom commented
@zregvart nice improvement in the UI from the original PR :)

2021-10-28 19:44 UTC, zregvart commented
> @zregvart nice improvement in the UI from the original PR :)

Still a bit awkward UX...