Fix (ENTESB-18466): do not rely on product name for operator condition
syndesisio/syndesis pull request #9944
Opened 2022-05-19 14:32 UTC by phantomjinx

* Operator-init looks up the deployment name by filtering
  on labels. Avoids need to specify the product name

2022-05-19 17:19 UTC, claudio4j requested changes
`operator-init` fails with
```
Info: Using POD_NAMESPACE:  syndesis
Info: Using Deployment Name:  syndesis-operator
Failed to set the upgrade condition on the operator: deployments.apps "syndesis-operator-operator" not found Error occurred
```
probably because in `operator_conditions.go` it adds the -operator suffix in line 75
```
deploymentName := productName + "-operator"
```

2022-05-23 12:52 UTC, phantomjinx commented
> `operator-init` fails with
> 
> ```
> Info: Using POD_NAMESPACE:  syndesis
> Info: Using Deployment Name:  syndesis-operator
> Failed to set the upgrade condition on the operator: deployments.apps "syndesis-operator-operator" not found Error occurred
> ```
> 
> probably because in `operator_conditions.go` it adds the -operator suffix in line 75
> 
> ```
> deploymentName := productName + "-operator"
> ```

Fixed.

2022-05-23 13:57 UTC, mkralik3 commented
sorry, I have rerun the eng job (174) with some changes and abort it and since the github takes the last one, it shows here as failed. The original job is still running here: https://fuse-7x-jenkins-csb-fuse-qe.apps.ocp-c1.prod.psi.redhat.com/job/fuse-7.11-syndesis-tests-PR-ENG/173

2022-05-23 16:22 UTC, claudio4j approved these changes

2022-05-23 16:23 UTC, merged